pipeline {
    agent {
    	kubernetes {
      		yamlFile 'prueba.yaml'
      		retries 2
    	}
    }

    environment {
        DOCKER_IMAGE_NAME = 'hanji96/billingapp-backend'
        POM_PATH = 'billing/pom.xml'
        DOCKERFILE_DIR = 'billing/Dockerfile'
        BUILD_TAG = "2.1.${env.BUILD_NUMBER}"
    }

    triggers {
        githubPush()
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: 'origin/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/HansJP96/practica_kubernetes1.git',
                        credentialsId: 'GitHub_Autenticacion_SSH'
                    ]],
                    extensions: []
                ])
            }
        }

        stage('Build Project') {
            steps {
                container(name: 'maven') {
                	sh 'ls -la'
                    // Compila el proyecto sin ejecutar las pruebas
                    sh """
                        mvn clean package -DskipTests -f ${env.POM_PATH}
                    """
                }
            }
        }

       
		stage('Build with Kaniko') {
  		environment {
    		PATH = "/busybox:/kaniko:$PATH"
  		}
  			steps {
    			container(name: 'kaniko', shell: '/busybox/sh') {
		
      			sh """#!/busybox/sh
        			/kaniko/executor --dockerfile `pwd`/${env.DOCKERFILE_DIR} --context `pwd` --verbosity debug \
        			--destination ${env.DOCKER_IMAGE_NAME}:${env.BUILD_TAG} --destination ${env.DOCKER_IMAGE_NAME}:latest
      			"""
    			}
  			}
		}
    }

    post {
        always {
            cleanWs()
        }
    }
}
