apiVersion: v1
kind: Pod
metadata:
  name: maven-kaniko
spec:
  affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: jenkins
                    operator: In
                    values:
                      - slave
  containers:
  - name: jnlp
    workingDir: /home/jenkins
  - name: maven 
    workingDir: /home/jenkins
    image: maven:3.9.9-eclipse-temurin-17-alpine
    imagePullPolicy: Always
  - name: kaniko
    workingDir: /home/jenkins
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: secret-docker
          items:
            - key: .dockerconfigjson
              path: config.json
